---
- hosts: all
  gather_facts: false
  vars_files:
  - vars/vtq.yml
  
  tasks:
  - include: tasks/pathogen-tasks.yml

  - include: tasks/pathogen-plugin-tasks.yml
    when: pathogen_plugin_urls is defined

  - include: tasks/copy-snippets.yml
    when: vimrc_snippets is defined
