---
- name: Clean up .vimrc.
  file: path=~/.vimrc state=absent

- name: Clean up the Vim directory.
  file: path=~/.vim state=absent

- name: Set up Vim directories.
  file: path={{ item }} state=directory
  with_items:
    - ~/.vim/plugin
    - "{{vtq_snippet_dir}}"
