---
- name: Copy vimrc snippet.
  copy: src="{{ item }}" dest="{{ vtq_snippet_dir }}/{{ item|basename }}"
  with_items: vimrc_snippets
  register: snippet_copy_register

- name: "Append snippets to vimrc."
  shell: "cat {{item.dest}} >> ~/.vimrc"
  when: item.changed
  with_items: snippet_copy_register.results
